#cloud-config

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCQFunM2YnQy0YD14WKeLvgXj/GTANwnNXl+vHbBO2VZ95kA0limE45TAeeZV1M5r9d9DjwFVQYQd/D/0Q6v4ozi6D5Ywu+ZNCtDnhGgZa3OKL6tMIdmM7WfIb3ieL8xGDiGslbcMoZPlSEZ5RNrSv4wR6ipRROK3Z54nNHh0gfqE1rPGBJkBdikGFoZJyDJbXrjQbKTAFcQLs0P+FjSL1oHc7EBl9EVi/aC08W2R+H2PSiZBfWqqZGCJ4kxQ7A+JO9Mtxn9VVU6tHHr2PwVyUPGf58SdfSc3U4esWehBnoeRQJT3kMOy055Xp7/BoAEKZQRXSJVU0ai/A2VEHxd59F aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key

ssh_pwauth: false # Ob es eine Password-Authentifizierung braucht
disable_root: false # Zeigt ob der root aktiviert ist oder nicht
package_update: true # Ob es die Packages updaten soll
packages: # Zeigt die Packages
  - curl
  - wget
  - mariadb-server
runcmd:
  - sudo apt update
  - sudo mysql -u root -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;"
  - sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
  - sudo systemctl restart mariadb.service
