#cloud-config                        

users:                                  # Benutzerkonfiguration
  - name: ubuntu                        # Benutzername
    sudo: ALL=(ALL) NOPASSWD:ALL        # sudo-regeln für diesen benutzer
    groups: users, admin                # Benutzer ist Mitglied in den Gruppen "users" und "admin"
    home: /home/ubuntu                  # Benutzerverzeichnis: /home/ubuntu
    shell: /bin/bash                    # Verwendete Shell: /bin/bash
    ssh_authorized_keys:                # SSH-öffentlicher Schlüssel zur Authentifizierung
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCQFunM2YnQy0YD14WKeLvgXj/GTANwnNXl+vHbBO2VZ95kA0limE45TAeeZV1M5r9d9DjwFVQYQd/D/0Q6v4ozi6D5Ywu+ZNCtDnhGgZa3OKL6tMIdmM7WfIb3ieL8xGDiGslbcMoZPlSEZ5RNrSv4wR6ipRROK3Z54nNHh0gfqE1rPGBJkBdikGFoZJyDJbXrjQbKTAFcQLs0P+FjSL1oHc7EBl9EVi/aC08W2R+H2PSiZBfWqqZGCJ4kxQ7A+JO9Mtxn9VVU6tHHr2PwVyUPGf58SdfSc3U4esWehBnoeRQJT3kMOy055Xp7/BoAEKZQRXSJVU0ai/A2VEHxd59F aws-key    # Öffentlicher SSH-Schlüssel
ssh_pwauth: false                       # SSH-Passwort-Authentifizierung ist deaktiviert
disable_root: false                     # Das Deaktivieren des Root-Benutzers ist deaktiviert
package_update: true                    # Paketaktualisierungen werden durchgeführt
packages:                               # Zusätzliche Pakete, die installiert werden
  - curl                                # Paket: curl
  - wget                                # Paket: wget
